// Writes COVERAGE.md from conformance/rows.ts (npm run coverage). Don't edit COVERAGE.md by hand.
import * as fs from 'fs';
import * as path from 'path';
import { GROUPS, ROWS } from '../conformance/rows';
import type { CoverageRow } from '../conformance/types';

const label = { yes: 'Yes', partial: 'Partial', no: 'No' } as const;
const strudelLabel = { yes: 'Yes', 'opt-in': 'Opt-in', no: 'No' } as const;
const cell = (s?: string) => (s ?? '—').replace(/\|/g, '\\|').replace(/\n/g, ' ');

function pct(rows: CoverageRow[]) {
  const yes = rows.filter((r) => r.covered === 'yes').length;
  const partial = rows.filter((r) => r.covered === 'partial').length;
  const n = rows.length;
  return {
    n,
    yes,
    partial,
    no: n - yes - partial,
    weighted: Math.round((100 * (yes + partial / 2)) / n),
    present: Math.round((100 * (yes + partial)) / n),
  };
}

const lines: string[] = [];
lines.push('# Web Audio API coverage on React Native');
lines.push('');
lines.push('<!-- Generated by scripts/gen-coverage.ts from conformance/rows.ts. Do not edit by hand. -->');
lines.push('');
lines.push(
  'Every piece of the standard Web Audio API, with whether a React Native app gets it through rn-web-audio-compat ' +
    '(on top of react-native-audio-api 0.13.5), how, where, and whether Strudel/superdough uses it. Each implemented row ' +
    'has a self-test: the example app runs it on React Native, and the web demo runs the identical test against the ' +
    "browser's own Web Audio API as the reference (one button per row in both; rows marked No have a disabled button)."
);
lines.push('');
lines.push('- **Covered?** Yes / Partial (works with a documented limit) / No.');
lines.push('- **How**: `react-native-audio-api` = provided by that library as is (sometimes with a fix from this library\'s patch); rn-web-audio-compat = added by this library.');
lines.push('- **Strudel?** Yes = used by normal Strudel patterns; Opt-in = only by a niche feature (audio device selection, visualisations, offline render); No = unused.');
lines.push('- **Savings left?** Remaining audio-thread CPU savings, and ones already made.');
lines.push('');
for (const group of GROUPS) {
  lines.push(`## ${group}`);
  lines.push('');
  lines.push('| Name | Covered? | How | Source | Strudel? | Savings left? | Self-test |');
  lines.push('|---|---|---|---|---|---|---|');
  for (const r of ROWS.filter((x) => x.group === group)) {
    lines.push(
      `| ${cell(r.name)} | ${label[r.covered]} | ${cell(r.how)} | ${cell(r.source)} | ${strudelLabel[r.strudel]} | ${cell(r.savings)} | ${r.test ? 'Yes' : '—'} |`
    );
  }
  lines.push('');
}
const all = pct(ROWS);
const strudel = pct(ROWS.filter((r) => r.strudel === 'yes'));
const strudelOptIn = pct(ROWS.filter((r) => r.strudel !== 'no'));
lines.push('## Coverage');
lines.push('');
lines.push('Counted per row (rows that group several members count once). Partial counts as half.');
lines.push('');
lines.push('| Scope | Rows | Yes | Partial | No | Coverage | Present at all |');
lines.push('|---|---|---|---|---|---|---|');
const line = (name: string, p: ReturnType<typeof pct>) =>
  `| ${name} | ${p.n} | ${p.yes} | ${p.partial} | ${p.no} | **${p.weighted}%** | ${p.present}% |`;
lines.push(line('Whole standard Web Audio API', all));
lines.push(line('What Strudel uses in normal patterns', strudel));
lines.push(line('What Strudel uses, including opt-in features', strudelOptIn));
lines.push('');
lines.push(
  'The biggest gaps (3D spatialization, media streams, latency reporting, output device selection, the deprecated ' +
    'ScriptProcessorNode) are ones Strudel never touches. Strudel-specific pieces (superdough\'s worklet processors, ' +
    'reverb, delay) are covered by [rn-strudel](https://github.com/wwrinkle/rn-strudel)\'s own COVERAGE.md.'
);
lines.push('');
lines.push('## Beyond the standard API');
lines.push('');
lines.push('- `FeedbackDelayNode`: a delay with feedback that works on react-native-audio-api (a DelayNode graph cycle does not: the library silently drops cycle edges). C++ kernel.');
lines.push('- `createFdnReverbNode()`: algorithmic reverb whose cost does not grow with its length (C++ kernel), level-matched to a browser\'s normalized ConvolverNode.');
lines.push('- `createAudioClock()`: setInterval/clearInterval driven by the audio thread, which keeps running with the screen locked on Android (plain JS timers stop).');
lines.push('- `startBackgroundPlayback()` / `stopBackgroundPlayback()`: the Android foreground-service notification that keeps audio alive under screen lock.');
lines.push('- `registerKernel()` / `createNativeKernelNode()`: run your own C++ DSP kernel in the graph (see native/README.md).');
lines.push('- `measureAudioLoad()`, `assertNativeKernels()`: audio-thread load and native build checks.');
lines.push('');
fs.writeFileSync(path.resolve(__dirname, '..', 'COVERAGE.md'), lines.join('\n'));
console.log(`COVERAGE.md: ${ROWS.length} rows; whole API ${all.weighted}%, Strudel ${strudel.weighted}%`);
